babl, gegl, gtk+3, gimp, gucharmap: new.

diff --git a/l/gegl/gegl.SlackBuild b/l/gegl/gegl.SlackBuild
--- a/l/gegl/gegl.SlackBuild
+++ b/l/gegl/gegl.SlackBuild
@@ -23,17 +23,7 @@
 
 
 VERSION=${VERSION:-$(echo gegl-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-2}
-
-# Automatically determine the architecture we're building on:
-if [ -z "$ARCH" ]; then
-  case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
-    arm*) export ARCH=arm ;;
-    # Unless $ARCH is already set, use uname -m for all other archs:
-       *) export ARCH=$( uname -m ) ;;
-  esac
-fi
+BUILD=${BUILD:-1}
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
@@ -41,19 +31,7 @@ CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-gegl
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "s390" ]; then
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
-else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
-fi
+set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG
@@ -68,14 +46,20 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
-CFLAGS="$SLKCFLAGS" \
+CFLAGS="-O2" \
 ./configure \
-  --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --docdir=/usr/doc/gegl-$VERSION \
-  --enable-gtk-doc \
+  --prefix=/${PREFIX} \
+  --libdir=/${PREFIX}/lib${LIBDIRSUFFIX} \
+  --docdir=/${PREFIX}/doc/gegl-$VERSION \
   --disable-docs \
-  --build=$ARCH-slackware-linux || exit 1
+  --without-sdl \
+  --build=${BUILD_TRIPLET} \
+  --host=${HOST_TRIPLET}
+
+# Had --enable-gtk-doc but it looks for gtk-doc through pkg-config and this
+# fails for cross-compilation.
+
+# We only have SDL2 and gegl only handles SDL(1).
 
 # Trust defaults:
 #  --enable-mmx \
@@ -84,26 +68,29 @@ CFLAGS="$SLKCFLAGS" \
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
 
-find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+find $PKG | xargs file | egrep -e "executable|shared object" \
+  | grep ${HOST_EXE_FORMAT} | cut -f 1 -d : \
+  | xargs ${HOST_STRIP} --strip-unneeded 2> /dev/null
 
-mkdir -p $PKG/usr/doc/gegl-$VERSION
+mkdir -p $PKG/${PREFIX}/doc/gegl-$VERSION
 cp -a \
-  AUTHORS COPYING* INSTALL NEWS README* TODO \
-  $PKG/usr/doc/gegl-$VERSION
-#( cd $PKG/usr/doc/gegl-$VERSION ; ln -s /usr/share/gtk-doc/html/gegl/ html )
+  AUTHORS COPYING* INSTALL NEWS README* \
+  $PKG/${PREFIX}/doc/gegl-$VERSION
+#( cd $PKG/${PREFIX}/doc/gegl-$VERSION ; ln -s /${PREFIX}/share/gtk-doc/html/gegl/ html )
 
 # If there's a ChangeLog, installing at least part of the recent history
 # is useful, but don't let it get totally out of control:
 if [ -r ChangeLog ]; then
-  DOCSDIR=$(echo $PKG/usr/doc/*-$VERSION)
+  DOCSDIR=$(echo $PKG/${PREFIX}/doc/*-$VERSION)
   cat ChangeLog | head -n 1000 > $DOCSDIR/ChangeLog
   touch -r ChangeLog $DOCSDIR/ChangeLog
 fi
 
-mkdir -p $PKG/install
-cat $CWD/slack-desc > $PKG/install/slack-desc
-
-cd $PKG
-/sbin/makepkg -l y -c n $TMP/gegl-$VERSION-$ARCH-$BUILD.txz
-
+cat ${CWD}/gegl.yypkg.script | sed \
+  -e "s/%{PKG}/gegl/" \
+  -e "s/%{HST}/${HOST_TRIPLET}/" \
+  -e "s/%{TGT}//" \
+  -e "s/%{VER}/${VERSION}/" \
+  -e "s/%{BUILD}/${BUILD}/" \
+  -e "s/%{DESCR}/${DESCR:-"No description"}/" \
+  | yypkg --makepkg --output ${YYOUTPUT} --script - --directory "${PKG}/${PREFIX}"
